nodeLinker: node-modules
enableScripts: false
npmMinimalAgeGate: 3d
npmPreapprovedPackages:
  - '@companion-module/*'

supportedArchitectures:
  os:
    - darwin
    - linux
    - win32
  cpu:
    - x64
    - arm64
    - ia32

